//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleSnail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleSnail.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter number of columns (maximum 10):.
        /// </summary>
        public static string ColumnValue {
            get {
                return ResourceManager.GetString("ColumnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of elements on main diagonal is:.
        /// </summary>
        public static string DiagonalSum {
            get {
                return ResourceManager.GetString("DiagonalSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1D Spiral Array:.
        /// </summary>
        public static string FirstResultStr {
            get {
                return ResourceManager.GetString("FirstResultStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Name: Snail
        ///* Function:
        ///- Users input matrix dimensions into the program (columns and lines).
        ///- Program fill matrix with random numbers (from 0 till 100 included).
        ///- More on github page
        ///* Author: Oleksandr Leoshko
        ///* Co-author: Maksym Oganesyan
        ///* Date: 14.03.2023
        ///* Copyright (c) 2023
        ///* All right reserved.
        /// </summary>
        public static string Greetings {
            get {
                return ResourceManager.GetString("Greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To restart app press Enter. Either Space to exit.
        /// </summary>
        public static string RestartOption {
            get {
                return ResourceManager.GetString("RestartOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter number of rows (maximum 10):.
        /// </summary>
        public static string RowValue {
            get {
                return ResourceManager.GetString("RowValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D Spiral Matrix:.
        /// </summary>
        public static string SecondResultStr {
            get {
                return ResourceManager.GetString("SecondResultStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please enter a number between 1 and 10..
        /// </summary>
        public static string ValueError {
            get {
                return ResourceManager.GetString("ValueError", resourceCulture);
            }
        }
    }
}
